---
- name: Check webpage for text and save results to CSV
  hosts: localhost
  gather_facts: no

  vars:
    target_url: "https://www.emag.ro/telefon-mobil-google-pixel-8-128gb-8gb-ram-5g-obsidian-ga05803-gb/pd/DFRGP1YBM/"
    # The text we are looking for in the webpage content.
    search_text: "Telefon mobil Google Pixel 8, 128GB, 8GB RAM, 5G, Obsidia"
    # Specify the path where you want to store the CSV file.
    csv_file: "/play/webcheck-save-output.csv"

  tasks:
    - name: Retrieve webpage content
      ansible.builtin.uri:
        url: "{{ target_url }}"
        method: GET
        return_content: yes
      register: webpage_response

    - name: Check for the text in the webpage content
      set_fact:
        text_found: "{{ 'true' if (search_text in webpage_response.content) else 'false' }}"

    - name: Extract <price> using regex
      set_fact:
        price: "{{ webpage_response.content | regex_search('<p class=\"product-new-price has-deal\" data-test=\"main-price\">(.*?)<sup><small class=\"mf-decimal\">,</small>00</sup> <span>Lei</span></p>', '\\1') }}"

    - name: Ensure CSV file exists with header
      # This will create the file with a header if it does not already exist.
      ansible.builtin.copy:
        dest: "{{ csv_file }}"
        content: "timestamp,url,text_found,price\n"
        force: no

    - name: Append check result to CSV file
      ansible.builtin.shell: |
        echo "{{ lookup('pipe','date +%Y-%m-%dT%H:%M:%S') }},{{ target_url }},{{ text_found }},{{ price }}" >> {{ csv_file }}
      args:
        #shell changed from '/bin/bash' to '/bin/sh' to avoid "msg": "[Errno 2] No such file or directory: b'/bin/bash'"
        executable: /bin/sh

    - name: Display CSV file contents (optional)
      ansible.builtin.command: cat {{ csv_file }}
      register: csv_content

    - name: Show CSV content
      ansible.builtin.debug:
        msg: "{{ csv_content.stdout }}"